### ISSUE TITLE
Discord Integration to the repository

### ISSUE THREAD

**Issue by natenaranjo** [Web3-Academy-DAO/w3pedia#6]
As of now all events on this repository will post to the discord channel #w3pedia-project.  If this becomes unbearable on the channel adjustment can be made through the repository settings => Webhooks => Which events..  Choose Customized Events and select which events you only want sent to the discord.

**Comment by imrishit98** [comment]
Thanks @natenaranjo!

**Comment by imrishit98** [comment]
Test!
